// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9thskNHMsVBlXyD8dPcE3Go8T8eeu0Yk',
    appId: '1:1034210306885:web:57397a30493bd18a562c2c',
    messagingSenderId: '1034210306885',
    projectId: 'ruang-tumbuh-45bf8',
    authDomain: 'ruang-tumbuh-45bf8.firebaseapp.com',
    storageBucket: 'ruang-tumbuh-45bf8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNd0tpIrmCqcXMnauoKYO1uBb_RmUv3M',
    appId: '1:1034210306885:android:ec2ecf849803784e562c2c',
    messagingSenderId: '1034210306885',
    projectId: 'ruang-tumbuh-45bf8',
    storageBucket: 'ruang-tumbuh-45bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1lxFD72OdHYrBzECDOPWcNWukP-A8No',
    appId: '1:1034210306885:ios:42ed09870134b23e562c2c',
    messagingSenderId: '1034210306885',
    projectId: 'ruang-tumbuh-45bf8',
    storageBucket: 'ruang-tumbuh-45bf8.firebasestorage.app',
    iosBundleId: 'com.example.ruangTumbuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1lxFD72OdHYrBzECDOPWcNWukP-A8No',
    appId: '1:1034210306885:ios:42ed09870134b23e562c2c',
    messagingSenderId: '1034210306885',
    projectId: 'ruang-tumbuh-45bf8',
    storageBucket: 'ruang-tumbuh-45bf8.firebasestorage.app',
    iosBundleId: 'com.example.ruangTumbuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9thskNHMsVBlXyD8dPcE3Go8T8eeu0Yk',
    appId: '1:1034210306885:web:f51e4a7360818b16562c2c',
    messagingSenderId: '1034210306885',
    projectId: 'ruang-tumbuh-45bf8',
    authDomain: 'ruang-tumbuh-45bf8.firebaseapp.com',
    storageBucket: 'ruang-tumbuh-45bf8.firebasestorage.app',
  );
}
